### ISSUE TITLE
How to exclude resource from linting but keep it in build stage?

### ISSUE THREAD

**Issue by hasitparmar-snyk** [snyk/vervet#409]
I have following folder structure for list of resources

```
.
└── src/
    ├── hidden/
    │   └── resources/
    │       ├── assignments/
    │       ├── lessons/
    │       ├── ai-bot/
    │       └── reports/
    └── rest/
        └── resources/
            ├── catalog/
            └── lessons/

```

And here is my .vervet.yaml configuration file:
```
linters:
  api-resource:
    description: Lint rules for individual API resource version specs
    optic-ci:
      script: node_modules/.bin/sweater-comb
apis:
  rest:
    resources:
      - path: 'src/rest/resources'
        linter: api-resource
        excludes:
            - 'src/rest/resources/stats/2024-08-29/spec.yaml'
            - 'src/rest/resources/education_resources/2024-05-13/spec.yaml'
            - 'src/rest/resources/assignments/2024-05-13/spec.yaml'

    overlays:
      - include: 'src/rest/overlays/openapi.yaml'
      - include: 'src/rest/overlays/security.yaml'
    output:
      paths:
        - 'dist/rest/versions'
        - 'src/rest/versions'
  hidden:
    resources:
      - path: 'src/hidden/resources'
        linter: api-resource
        excludes:
            - 'src/hidden/resources/ai-bot/2024-10-15/spec.yaml'

    overlays:
      - include: 'src/hidden/overlays/openapi.yaml'
      - include: 'src/hidden/overlays/security.yaml'
    output:
      paths:
        - 'dist/hidden/versions'
        - 'src/hidden/versions'
```
I want to exclude the hidden/ai-bot resource from sweater-comb linting but still include it in the vervet build process. Right now, I have added it to the excludes list, which makes it skip both linting and building.

Is there a way to disable sweater-comb linting for this resource while keeping it in the build process?
